name: flutter_duo_practice
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  just_audio: ^0.9.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
   - family: Comfortaa
     fonts:
      - asset: assets/fonts/Comfortaa/Comfortaa-Bold.ttf
        weight: 700
      - asset: assets/fonts/Comfortaa/Comfortaa-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Comfortaa/Comfortaa-Medium.ttf
        weight: 500
      - asset: assets/fonts/Comfortaa/Comfortaa-Regular.ttf
        weight: 400
      - asset: assets/fonts/Comfortaa/Comfortaa-Light.ttf
        weight: 200

  assets:
    - assets/images/
    - assets/images/subcategories_backgrounds/
    - assets/music/